#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EvalCorridorExit_BP

#include "Basic.hpp"

#include "EvalCorridorExit_BP_classes.hpp"
#include "EvalCorridorExit_BP_parameters.hpp"


namespace SDK
{

// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.UpdateShadowVisual
// (Public, BlueprintCallable, BlueprintEvent)

void AEvalCorridorExit_BP_C::UpdateShadowVisual()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "UpdateShadowVisual");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.ForceLightDisabled
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Disabled                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEvalCorridorExit_BP_C::ForceLightDisabled(bool Disabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "ForceLightDisabled");

	Params::EvalCorridorExit_BP_C_ForceLightDisabled Parms{};

	Parms.Disabled = Disabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.UpdateTubeLighting
// (Public, BlueprintCallable, BlueprintEvent)

void AEvalCorridorExit_BP_C::UpdateTubeLighting()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "UpdateTubeLighting");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.OnActivationChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    LightsEnabled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEvalCorridorExit_BP_C::OnActivationChanged(bool LightsEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "OnActivationChanged");

	Params::EvalCorridorExit_BP_C_OnActivationChanged Parms{};

	Parms.LightsEnabled = LightsEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.ApplyLightChannel
// (Public, BlueprintCallable, BlueprintEvent)

void AEvalCorridorExit_BP_C::ApplyLightChannel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "ApplyLightChannel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UStaticMeshComponent*             Red_Light                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UStaticMeshComponent*             Green_Light                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   FogIntensity                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEvalCorridorExit_BP_C::Initialize(class UStaticMeshComponent* Red_Light, class UStaticMeshComponent* Green_Light, float FogIntensity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "Initialize");

	Params::EvalCorridorExit_BP_C_Initialize Parms{};

	Parms.Red_Light = Red_Light;
	Parms.Green_Light = Green_Light;
	Parms.FogIntensity = FogIntensity;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AEvalCorridorExit_BP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void AEvalCorridorExit_BP_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void AEvalCorridorExit_BP_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AEvalCorridorExit_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.Open
// (BlueprintCallable, BlueprintEvent)

void AEvalCorridorExit_BP_C::Open()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "Open");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.Close
// (BlueprintCallable, BlueprintEvent)

void AEvalCorridorExit_BP_C::Close()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "Close");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.Event_OnLocalPlayerEntered
// (Event, Public, BlueprintEvent)

void AEvalCorridorExit_BP_C::Event_OnLocalPlayerEntered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "Event_OnLocalPlayerEntered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.Event_OnLocalPlayerExited
// (Event, Public, BlueprintEvent)

void AEvalCorridorExit_BP_C::Event_OnLocalPlayerExited()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "Event_OnLocalPlayerExited");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.ExecuteUbergraph_EvalCorridorExit_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEvalCorridorExit_BP_C::ExecuteUbergraph_EvalCorridorExit_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "ExecuteUbergraph_EvalCorridorExit_BP");

	Params::EvalCorridorExit_BP_C_ExecuteUbergraph_EvalCorridorExit_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.OnOpenedStageChanged__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASASTubeMinus02_BP_C*             SASTube                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEvalCorridorExit_BP_C::OnOpenedStageChanged__DelegateSignature(class ASASTubeMinus02_BP_C* SASTube)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "OnOpenedStageChanged__DelegateSignature");

	Params::EvalCorridorExit_BP_C_OnOpenedStageChanged__DelegateSignature Parms{};

	Parms.SASTube = SASTube;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.AnimationCompletedBackward__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void AEvalCorridorExit_BP_C::AnimationCompletedBackward__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "AnimationCompletedBackward__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EvalCorridorExit_BP.EvalCorridorExit_BP_C.AnimationCompletedForward__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void AEvalCorridorExit_BP_C::AnimationCompletedForward__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EvalCorridorExit_BP_C", "AnimationCompletedForward__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

