#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FlipCounterMinusBP

#include "Basic.hpp"

#include "FlipCounterMinusBP_classes.hpp"
#include "FlipCounterMinusBP_parameters.hpp"


namespace SDK
{

// Function FlipCounter-BP.FlipCounter-BP_C.GetCounter
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 AFlipCounterMinusBP_C::GetCounter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipCounter-BP_C", "GetCounter");

	Params::FlipCounterMinusBP_C_GetCounter Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function FlipCounter-BP.FlipCounter-BP_C.Decrement
// (Public, BlueprintCallable, BlueprintEvent)

void AFlipCounterMinusBP_C::Decrement()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipCounter-BP_C", "Decrement");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipCounter-BP.FlipCounter-BP_C.Increment
// (Public, BlueprintCallable, BlueprintEvent)

void AFlipCounterMinusBP_C::Increment()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipCounter-BP_C", "Increment");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipCounter-BP.FlipCounter-BP_C.OnRep_currentCountNumber
// (BlueprintCallable, BlueprintEvent)

void AFlipCounterMinusBP_C::OnRep_currentCountNumber()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipCounter-BP_C", "OnRep_currentCountNumber");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipCounter-BP.FlipCounter-BP_C.OnRep_initialCountNumber
// (BlueprintCallable, BlueprintEvent)

void AFlipCounterMinusBP_C::OnRep_initialCountNumber()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipCounter-BP_C", "OnRep_initialCountNumber");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipCounter-BP.FlipCounter-BP_C.ResetCount
// (Public, BlueprintCallable, BlueprintEvent)

void AFlipCounterMinusBP_C::ResetCount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipCounter-BP_C", "ResetCount");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipCounter-BP.FlipCounter-BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AFlipCounterMinusBP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipCounter-BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipCounter-BP.FlipCounter-BP_C.Event_OnResetStage
// (Event, Public, BlueprintEvent)

void AFlipCounterMinusBP_C::Event_OnResetStage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipCounter-BP_C", "Event_OnResetStage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipCounter-BP.FlipCounter-BP_C.Update Visual
// (BlueprintCallable, BlueprintEvent)

void AFlipCounterMinusBP_C::Update_Visual()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipCounter-BP_C", "Update Visual");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipCounter-BP.FlipCounter-BP_C.SetCounter
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFlipCounterMinusBP_C::SetCounter(int32 Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipCounter-BP_C", "SetCounter");

	Params::FlipCounterMinusBP_C_SetCounter Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FlipCounter-BP.FlipCounter-BP_C.ExecuteUbergraph_FlipCounter-BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFlipCounterMinusBP_C::ExecuteUbergraph_FlipCounterMinusBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipCounter-BP_C", "ExecuteUbergraph_FlipCounter-BP");

	Params::FlipCounterMinusBP_C_ExecuteUbergraph_FlipCounterMinusBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

