#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenu

#include "Basic.hpp"

#include "MainMenu_classes.hpp"
#include "MainMenu_parameters.hpp"


namespace SDK
{

// Function MainMenu.MainMenu_C.ToggleXPCheck
// (BlueprintCallable, BlueprintEvent)

void AMainMenu_C::ToggleXPCheck()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "ToggleXPCheck");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AMainMenu_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMainMenu_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "ReceiveEndPlay");

	Params::MainMenu_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu.MainMenu_C.MM_PlayCamera01
// (Net, NetClient, BlueprintCallable, BlueprintEvent)

void AMainMenu_C::MM_PlayCamera01()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "MM_PlayCamera01");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.MM_PlayCamera-02
// (Net, NetClient, BlueprintCallable, BlueprintEvent)

void AMainMenu_C::MM_PlayCameraMinus02()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "MM_PlayCamera-02");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.MM_StopCamera01
// (BlueprintCallable, BlueprintEvent)

void AMainMenu_C::MM_StopCamera01()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "MM_StopCamera01");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.MM_StopCamera-02
// (BlueprintCallable, BlueprintEvent)

void AMainMenu_C::MM_StopCameraMinus02()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "MM_StopCamera-02");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.OnMainMenuStageChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EMainMenuState                          MainMenuState                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMainMenu_C::OnMainMenuStageChanged(EMainMenuState MainMenuState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnMainMenuStageChanged");

	Params::MainMenu_C_OnMainMenuStageChanged Parms{};

	Parms.MainMenuState = MainMenuState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu.MainMenu_C.MM_Scratch
// (BlueprintCallable, BlueprintEvent)

void AMainMenu_C::MM_Scratch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "MM_Scratch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.MM_ScratchClose
// (BlueprintCallable, BlueprintEvent)

void AMainMenu_C::MM_ScratchClose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "MM_ScratchClose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.ExecuteUbergraph_MainMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMainMenu_C::ExecuteUbergraph_MainMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "ExecuteUbergraph_MainMenu");

	Params::MainMenu_C_ExecuteUbergraph_MainMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

