#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerkSlotsButton

#include "Basic.hpp"

#include "PerkSlotsButton_classes.hpp"
#include "PerkSlotsButton_parameters.hpp"


namespace SDK
{

// Function PerkSlotsButton.PerkSlotsButton_C.OnRemovedFromFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UPerkSlotsButton_C::OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "OnRemovedFromFocusPath");

	Params::PerkSlotsButton_C_OnRemovedFromFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkSlotsButton.PerkSlotsButton_C.SetFocused
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bInFocused                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPerkSlotsButton_C::SetFocused(bool bInFocused)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "SetFocused");

	Params::PerkSlotsButton_C_SetFocused Parms{};

	Parms.bInFocused = bInFocused;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkSlotsButton.PerkSlotsButton_C.IsConsideredHovered
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    bConsideredHovered                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPerkSlotsButton_C::IsConsideredHovered(bool* bConsideredHovered)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "IsConsideredHovered");

	Params::PerkSlotsButton_C_IsConsideredHovered Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bConsideredHovered != nullptr)
		*bConsideredHovered = Parms.bConsideredHovered;
}


// Function PerkSlotsButton.PerkSlotsButton_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UPerkSlotsButton_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "OnFocusReceived");

	Params::PerkSlotsButton_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function PerkSlotsButton.PerkSlotsButton_C.SetHovered
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bInHovered                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPerkSlotsButton_C::SetHovered(bool bInHovered)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "SetHovered");

	Params::PerkSlotsButton_C_SetHovered Parms{};

	Parms.bInHovered = bInHovered;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkSlotsButton.PerkSlotsButton_C.Refresh
// (Public, BlueprintCallable, BlueprintEvent)

void UPerkSlotsButton_C::Refresh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "Refresh");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PerkSlotsButton.PerkSlotsButton_C.Init
// (Public, BlueprintCallable, BlueprintEvent)

void UPerkSlotsButton_C::Init()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "Init");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PerkSlotsButton.PerkSlotsButton_C.Setup
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UPerkSlotsButton_C::Setup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "Setup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PerkSlotsButton.PerkSlotsButton_C.BndEvt__RigButton_InteractionButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UPerkSlotsButton_C::BndEvt__RigButton_InteractionButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "BndEvt__RigButton_InteractionButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PerkSlotsButton.PerkSlotsButton_C.BndEvt__RigButton_InteractionButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UPerkSlotsButton_C::BndEvt__RigButton_InteractionButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "BndEvt__RigButton_InteractionButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PerkSlotsButton.PerkSlotsButton_C.BndEvt__RigButton_InteractionButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UPerkSlotsButton_C::BndEvt__RigButton_InteractionButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "BndEvt__RigButton_InteractionButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PerkSlotsButton.PerkSlotsButton_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UPerkSlotsButton_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PerkSlotsButton.PerkSlotsButton_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UPerkSlotsButton_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PerkSlotsButton.PerkSlotsButton_C.OnMenuInputSourceChanged
// (BlueprintCallable, BlueprintEvent)

void UPerkSlotsButton_C::OnMenuInputSourceChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "OnMenuInputSourceChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PerkSlotsButton.PerkSlotsButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPerkSlotsButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "PreConstruct");

	Params::PerkSlotsButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkSlotsButton.PerkSlotsButton_C.ExecuteUbergraph_PerkSlotsButton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPerkSlotsButton_C::ExecuteUbergraph_PerkSlotsButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "ExecuteUbergraph_PerkSlotsButton");

	Params::PerkSlotsButton_C_ExecuteUbergraph_PerkSlotsButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PerkSlotsButton.PerkSlotsButton_C.OnClicked__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UPerkSlotsButton_C::OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PerkSlotsButton_C", "OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

