#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Speaker_BP

#include "Basic.hpp"

#include "Speaker_BP_classes.hpp"
#include "Speaker_BP_parameters.hpp"


namespace SDK
{

// Function Speaker_BP.Speaker_BP_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ASpeaker_BP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Speaker_BP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

