#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CellCustomizationObjectType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum CellCustomizationObjectType.CellCustomizationObjectType
// NumValues: 0x0003
enum class ECellCustomizationObjectType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	CellCustomizationObjectType_MAX          = 2,
};

}

