#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CellCustomizationBundleBase

#include "Basic.hpp"

#include "CellCustomizationBundleBase_classes.hpp"
#include "CellCustomizationBundleBase_parameters.hpp"


namespace SDK
{

// Function CellCustomizationBundleBase.CellCustomizationBundleBase_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ACellCustomizationBundleBase_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CellCustomizationBundleBase_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

