#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Denizen_Face_Blinks_Notify

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Denizen_Face_Blinks_Notify.Denizen_Face_Blinks_Notify_C
// 0x0008 (0x0040 - 0x0038)
class UDenizen_Face_Blinks_Notify_C final : public UAnimNotify
{
public:
	bool                                          HalfBlink;                                         // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	bool IsBlinking(class USkeletalMeshComponent* Mesh_Comp) const;
	bool Received_Notify(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation) const;
	class FString GetNotifyName() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Denizen_Face_Blinks_Notify_C">();
	}
	static class UDenizen_Face_Blinks_Notify_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDenizen_Face_Blinks_Notify_C>();
	}
};
static_assert(alignof(UDenizen_Face_Blinks_Notify_C) == 0x000008, "Wrong alignment on UDenizen_Face_Blinks_Notify_C");
static_assert(sizeof(UDenizen_Face_Blinks_Notify_C) == 0x000040, "Wrong size on UDenizen_Face_Blinks_Notify_C");
static_assert(offsetof(UDenizen_Face_Blinks_Notify_C, HalfBlink) == 0x000038, "Member 'UDenizen_Face_Blinks_Notify_C::HalfBlink' has a wrong offset!");

}

