#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GasCanister_NonPickable_BP

#include "Basic.hpp"

#include "GasCanister_NonPickable_BP_classes.hpp"
#include "GasCanister_NonPickable_BP_parameters.hpp"


namespace SDK
{

// Function GasCanister_NonPickable_BP.GasCanister_NonPickable_BP_C.ExecuteUbergraph_GasCanister_NonPickable_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGasCanister_NonPickable_BP_C::ExecuteUbergraph_GasCanister_NonPickable_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GasCanister_NonPickable_BP_C", "ExecuteUbergraph_GasCanister_NonPickable_BP");

	Params::GasCanister_NonPickable_BP_C_ExecuteUbergraph_GasCanister_NonPickable_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GasCanister_NonPickable_BP.GasCanister_NonPickable_BP_C.Untrigger
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AGasCanister_NonPickable_BP_C::Untrigger()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GasCanister_NonPickable_BP_C", "Untrigger");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GasCanister_NonPickable_BP.GasCanister_NonPickable_BP_C.Trigger
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AGasCanister_NonPickable_BP_C::Trigger()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GasCanister_NonPickable_BP_C", "Trigger");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GasCanister_NonPickable_BP.GasCanister_NonPickable_BP_C.BndEvt__GasCanister_NonPickable_BP_RBPropOptimizer_K2Node_ComponentBoundEvent_0_PropOptimizerComponentTickEnabledChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bEnabled                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AGasCanister_NonPickable_BP_C::BndEvt__GasCanister_NonPickable_BP_RBPropOptimizer_K2Node_ComponentBoundEvent_0_PropOptimizerComponentTickEnabledChangedEvent__DelegateSignature(bool bEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GasCanister_NonPickable_BP_C", "BndEvt__GasCanister_NonPickable_BP_RBPropOptimizer_K2Node_ComponentBoundEvent_0_PropOptimizerComponentTickEnabledChangedEvent__DelegateSignature");

	Params::GasCanister_NonPickable_BP_C_BndEvt__GasCanister_NonPickable_BP_RBPropOptimizer_K2Node_ComponentBoundEvent_0_PropOptimizerComponentTickEnabledChangedEvent__DelegateSignature Parms{};

	Parms.bEnabled = bEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GasCanister_NonPickable_BP.GasCanister_NonPickable_BP_C.OnWorldPopulateFinished
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AGasCanister_NonPickable_BP_C::OnWorldPopulateFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GasCanister_NonPickable_BP_C", "OnWorldPopulateFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GasCanister_NonPickable_BP.GasCanister_NonPickable_BP_C.OnWorldFullyLoaded
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AGasCanister_NonPickable_BP_C::OnWorldFullyLoaded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GasCanister_NonPickable_BP_C", "OnWorldFullyLoaded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GasCanister_NonPickable_BP.GasCanister_NonPickable_BP_C.TestGasDirection
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          Direction                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bClear                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AGasCanister_NonPickable_BP_C::TestGasDirection(const struct FVector& Direction, bool* bClear)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GasCanister_NonPickable_BP_C", "TestGasDirection");

	Params::GasCanister_NonPickable_BP_C_TestGasDirection Parms{};

	Parms.Direction = std::move(Direction);

	UObject::ProcessEvent(Func, &Parms);

	if (bClear != nullptr)
		*bClear = Parms.bClear;
}


// Function GasCanister_NonPickable_BP.GasCanister_NonPickable_BP_C.OnRep_bTriggered
// (BlueprintCallable, BlueprintEvent)

void AGasCanister_NonPickable_BP_C::OnRep_bTriggered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GasCanister_NonPickable_BP_C", "OnRep_bTriggered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GasCanister_NonPickable_BP.GasCanister_NonPickable_BP_C.RefreshVFXActive
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AGasCanister_NonPickable_BP_C::RefreshVFXActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GasCanister_NonPickable_BP_C", "RefreshVFXActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GasCanister_NonPickable_BP.GasCanister_NonPickable_BP_C.OnWorldPopulateFinishedTimeSliced
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool AGasCanister_NonPickable_BP_C::OnWorldPopulateFinishedTimeSliced()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GasCanister_NonPickable_BP_C", "OnWorldPopulateFinishedTimeSliced");

	Params::GasCanister_NonPickable_BP_C_OnWorldPopulateFinishedTimeSliced Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function GasCanister_NonPickable_BP.GasCanister_NonPickable_BP_C.IsTriggered
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool AGasCanister_NonPickable_BP_C::IsTriggered() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GasCanister_NonPickable_BP_C", "IsTriggered");

	Params::GasCanister_NonPickable_BP_C_IsTriggered Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

