#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GroupLeaderDisclaimerScrollStyle

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GroupLeaderDisclaimerScrollStyle.GroupLeaderDisclaimerScrollStyle_C
// 0x0000 (0x0040 - 0x0040)
class UGroupLeaderDisclaimerScrollStyle_C final : public UCommonTextScrollStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GroupLeaderDisclaimerScrollStyle_C">();
	}
	static class UGroupLeaderDisclaimerScrollStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGroupLeaderDisclaimerScrollStyle_C>();
	}
};
static_assert(alignof(UGroupLeaderDisclaimerScrollStyle_C) == 0x000008, "Wrong alignment on UGroupLeaderDisclaimerScrollStyle_C");
static_assert(sizeof(UGroupLeaderDisclaimerScrollStyle_C) == 0x000040, "Wrong size on UGroupLeaderDisclaimerScrollStyle_C");

}

