#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LobbyScientistInterface

#include "Basic.hpp"


namespace SDK::Params
{

// Function LobbyScientistInterface.LobbyScientistInterface_C.SetPenMeshVisible
// 0x0001 (0x0001 - 0x0000)
struct LobbyScientistInterface_C_SetPenMeshVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(LobbyScientistInterface_C_SetPenMeshVisible) == 0x000001, "Wrong alignment on LobbyScientistInterface_C_SetPenMeshVisible");
static_assert(sizeof(LobbyScientistInterface_C_SetPenMeshVisible) == 0x000001, "Wrong size on LobbyScientistInterface_C_SetPenMeshVisible");
static_assert(offsetof(LobbyScientistInterface_C_SetPenMeshVisible, Visible) == 0x000000, "Member 'LobbyScientistInterface_C_SetPenMeshVisible::Visible' has a wrong offset!");

}

