#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WallSide_Enu

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum WallSide_Enu.WallSide_Enu
// NumValues: 0x0004
enum class EWallSide_Enu : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	WallSide_MAX                             = 3,
};

}

