#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Base_Movable_Button_BP

#include "Basic.hpp"

#include "Base_Movable_Button_BP_classes.hpp"
#include "Base_Movable_Button_BP_parameters.hpp"


namespace SDK
{

// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.FixUp
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool ABase_Movable_Button_BP_C::FixUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "FixUp");

	Params::Base_Movable_Button_BP_C_FixUp Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.OnRep_bLocked
// (BlueprintCallable, BlueprintEvent)

void ABase_Movable_Button_BP_C::OnRep_bLocked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "OnRep_bLocked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.UpdateButtonPosition
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABase_Movable_Button_BP_C::UpdateButtonPosition(float Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "UpdateButtonPosition");

	Params::Base_Movable_Button_BP_C_UpdateButtonPosition Parms{};

	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABase_Movable_Button_BP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.ButtonLiftTimeline__FinishedFunc
// (BlueprintEvent)

void ABase_Movable_Button_BP_C::ButtonLiftTimeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "ButtonLiftTimeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.ButtonLiftTimeline__UpdateFunc
// (BlueprintEvent)

void ABase_Movable_Button_BP_C::ButtonLiftTimeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "ButtonLiftTimeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.OnPostActorsPasted
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// TArray<class AActor*>                   PastedActors                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABase_Movable_Button_BP_C::OnPostActorsPasted(const TArray<class AActor*>& PastedActors)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "OnPostActorsPasted");

	Params::Base_Movable_Button_BP_C_OnPostActorsPasted Parms{};

	Parms.PastedActors = std::move(PastedActors);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.PostAddedToLevel
// (Event, Public, BlueprintEvent)

void ABase_Movable_Button_BP_C::PostAddedToLevel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "PostAddedToLevel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.PostDuplicated
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           DuplicationParent                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABase_Movable_Button_BP_C::PostDuplicated(class AActor* DuplicationParent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "PostDuplicated");

	Params::Base_Movable_Button_BP_C_PostDuplicated Parms{};

	Parms.DuplicationParent = DuplicationParent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.PostEditChange
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class FName                             PropertyName                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABase_Movable_Button_BP_C::PostEditChange(const class FName& PropertyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "PostEditChange");

	Params::Base_Movable_Button_BP_C_PostEditChange Parms{};

	Parms.PropertyName = PropertyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.PostEditMove
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bFinished                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABase_Movable_Button_BP_C::PostEditMove(bool bFinished)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "PostEditMove");

	Params::Base_Movable_Button_BP_C_PostEditMove Parms{};

	Parms.bFinished = bFinished;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.TickSelected
// (Event, Public, BlueprintEvent)

void ABase_Movable_Button_BP_C::TickSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "TickSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.EnableVisual
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Enable                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABase_Movable_Button_BP_C::EnableVisual(bool Enable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "EnableVisual");

	Params::Base_Movable_Button_BP_C_EnableVisual Parms{};

	Parms.Enable = Enable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.Event_OnResetStage
// (Event, Public, BlueprintEvent)

void ABase_Movable_Button_BP_C::Event_OnResetStage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "Event_OnResetStage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.OnUnlocked
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABase_Movable_Button_BP_C::OnUnlocked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "OnUnlocked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.OnLocked
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABase_Movable_Button_BP_C::OnLocked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "OnLocked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.Lock
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABase_Movable_Button_BP_C::Lock()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "Lock");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.Unlock
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ARBPawn*                          Pawn                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABase_Movable_Button_BP_C::Unlock(class ARBPawn* Pawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "Unlock");

	Params::Base_Movable_Button_BP_C_Unlock Parms{};

	Parms.Pawn = Pawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.OnEditorPostLoad
// (Event, Public, BlueprintEvent)

void ABase_Movable_Button_BP_C::OnEditorPostLoad()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "OnEditorPostLoad");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.ExecuteUbergraph_Base_Movable_Button_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABase_Movable_Button_BP_C::ExecuteUbergraph_Base_Movable_Button_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "ExecuteUbergraph_Base_Movable_Button_BP");

	Params::Base_Movable_Button_BP_C_ExecuteUbergraph_Base_Movable_Button_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Base_Movable_Button_BP.Base_Movable_Button_BP_C.IsLocked
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool ABase_Movable_Button_BP_C::IsLocked() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Base_Movable_Button_BP_C", "IsLocked");

	Params::Base_Movable_Button_BP_C_IsLocked Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

