#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BASE_ElectricalSwitchMinus01_BP

#include "Basic.hpp"

#include "BASE_ElectricalSwitchMinus01_BP_classes.hpp"
#include "BASE_ElectricalSwitchMinus01_BP_parameters.hpp"


namespace SDK
{

// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.OnWaitingForResetCompletedChanged__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void ABASE_ElectricalSwitchMinus01_BP_C::OnWaitingForResetCompletedChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "OnWaitingForResetCompletedChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.ExecuteUbergraph_BASE_ElectricalSwitch-01_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABASE_ElectricalSwitchMinus01_BP_C::ExecuteUbergraph_BASE_ElectricalSwitchMinus01_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "ExecuteUbergraph_BASE_ElectricalSwitch-01_BP");

	Params::BASE_ElectricalSwitchMinus01_BP_C_ExecuteUbergraph_BASE_ElectricalSwitchMinus01_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.Event_OnInteractorsChangedEvent
// (Event, Public, BlueprintEvent)

void ABASE_ElectricalSwitchMinus01_BP_C::Event_OnInteractorsChangedEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "Event_OnInteractorsChangedEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABASE_ElectricalSwitchMinus01_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.Event_OnResetStage
// (Event, Public, BlueprintEvent)

void ABASE_ElectricalSwitchMinus01_BP_C::Event_OnResetStage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "Event_OnResetStage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.Event_OnTimedReset
// (Event, Public, BlueprintEvent)

void ABASE_ElectricalSwitchMinus01_BP_C::Event_OnTimedReset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "Event_OnTimedReset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.Event_SnapToState
// (Event, Public, BlueprintEvent)

void ABASE_ElectricalSwitchMinus01_BP_C::Event_SnapToState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "Event_SnapToState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.Event_OnCompletedOperation
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// TArray<class ARBPawn*>                  Pawns                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABASE_ElectricalSwitchMinus01_BP_C::Event_OnCompletedOperation(const TArray<class ARBPawn*>& Pawns)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "Event_OnCompletedOperation");

	Params::BASE_ElectricalSwitchMinus01_BP_C_Event_OnCompletedOperation Parms{};

	Parms.Pawns = std::move(Pawns);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.SetTriggerableActivation
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Condition                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class ARBTriggerable*                   RBTriggerable                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABASE_ElectricalSwitchMinus01_BP_C::SetTriggerableActivation(bool Condition, class ARBTriggerable* RBTriggerable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "SetTriggerableActivation");

	Params::BASE_ElectricalSwitchMinus01_BP_C_SetTriggerableActivation Parms{};

	Parms.Condition = Condition;
	Parms.RBTriggerable = RBTriggerable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.Event_OnOperationProgressChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   CurrentProgressRatio                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABASE_ElectricalSwitchMinus01_BP_C::Event_OnOperationProgressChanged(float CurrentProgressRatio)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "Event_OnOperationProgressChanged");

	Params::BASE_ElectricalSwitchMinus01_BP_C_Event_OnOperationProgressChanged Parms{};

	Parms.CurrentProgressRatio = CurrentProgressRatio;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABASE_ElectricalSwitchMinus01_BP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.SetCableHeight
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABASE_ElectricalSwitchMinus01_BP_C::SetCableHeight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "SetCableHeight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.SetWaitingForResetCompleted
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABASE_ElectricalSwitchMinus01_BP_C::SetWaitingForResetCompleted(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "SetWaitingForResetCompleted");

	Params::BASE_ElectricalSwitchMinus01_BP_C_SetWaitingForResetCompleted Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.RefreshLightMaterial
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   CurrentLight                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             MaterialName                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UMaterialInterface*               Material                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bChanged                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABASE_ElectricalSwitchMinus01_BP_C::RefreshLightMaterial(int32 CurrentLight, class FName MaterialName, class UMaterialInterface* Material, bool* bChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "RefreshLightMaterial");

	Params::BASE_ElectricalSwitchMinus01_BP_C_RefreshLightMaterial Parms{};

	Parms.CurrentLight = CurrentLight;
	Parms.MaterialName = MaterialName;
	Parms.Material = Material;

	UObject::ProcessEvent(Func, &Parms);

	if (bChanged != nullptr)
		*bChanged = Parms.bChanged;
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.HasInteractingPawn
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    Value                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABASE_ElectricalSwitchMinus01_BP_C::HasInteractingPawn(bool* Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "HasInteractingPawn");

	Params::BASE_ElectricalSwitchMinus01_BP_C_HasInteractingPawn Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Value != nullptr)
		*Value = Parms.Value;
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.RefreshLightDisplay
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABASE_ElectricalSwitchMinus01_BP_C::RefreshLightDisplay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "RefreshLightDisplay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.ShouldAllLightBeOn
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    bAllLightOn                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABASE_ElectricalSwitchMinus01_BP_C::ShouldAllLightBeOn(bool* bAllLightOn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "ShouldAllLightBeOn");

	Params::BASE_ElectricalSwitchMinus01_BP_C_ShouldAllLightBeOn Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bAllLightOn != nullptr)
		*bAllLightOn = Parms.bAllLightOn;
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.TestPhysicsClearance
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class ARBPawn*                          InteractorPawn                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool ABASE_ElectricalSwitchMinus01_BP_C::TestPhysicsClearance(const class ARBPawn* InteractorPawn) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "TestPhysicsClearance");

	Params::BASE_ElectricalSwitchMinus01_BP_C_TestPhysicsClearance Parms{};

	Parms.InteractorPawn = InteractorPawn;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BASE_ElectricalSwitch-01_BP.BASE_ElectricalSwitch-01_BP_C.GetInteractionPawnLocation
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class ARBPawn*                          Pawn                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ESpecialMove                            SpecialMove                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          OutLocation                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          OutDirection                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool ABASE_ElectricalSwitchMinus01_BP_C::GetInteractionPawnLocation(const class ARBPawn* Pawn, ESpecialMove SpecialMove, struct FVector* OutLocation, struct FVector* OutDirection) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BASE_ElectricalSwitch-01_BP_C", "GetInteractionPawnLocation");

	Params::BASE_ElectricalSwitchMinus01_BP_C_GetInteractionPawnLocation Parms{};

	Parms.Pawn = Pawn;
	Parms.SpecialMove = SpecialMove;

	UObject::ProcessEvent(Func, &Parms);

	if (OutLocation != nullptr)
		*OutLocation = std::move(Parms.OutLocation);

	if (OutDirection != nullptr)
		*OutDirection = std::move(Parms.OutDirection);

	return Parms.ReturnValue;
}

}

