#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CeilingLampMinus10

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CeilingBulbLightBaseMinus02_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CeilingLamp-10.CeilingLamp-10_C
// 0x0010 (0x07B0 - 0x07A0)
class ACeilingLampMinus10_C final : public ACeilingBulbLightBaseMinus02_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_CeilingLampMinus10_C;               // 0x0798(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          UseBounceLight;                                    // 0x07A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ReceiveActorBeginOverlap(class AActor* OtherActor);
	void ExecuteUbergraph_CeilingLampMinus10(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CeilingLamp-10_C">();
	}
	static class ACeilingLampMinus10_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACeilingLampMinus10_C>();
	}
};
static_assert(alignof(ACeilingLampMinus10_C) == 0x000010, "Wrong alignment on ACeilingLampMinus10_C");
static_assert(sizeof(ACeilingLampMinus10_C) == 0x0007B0, "Wrong size on ACeilingLampMinus10_C");
static_assert(offsetof(ACeilingLampMinus10_C, UberGraphFrame_CeilingLampMinus10_C) == 0x000798, "Member 'ACeilingLampMinus10_C::UberGraphFrame_CeilingLampMinus10_C' has a wrong offset!");
static_assert(offsetof(ACeilingLampMinus10_C, UseBounceLight) == 0x0007A0, "Member 'ACeilingLampMinus10_C::UseBounceLight' has a wrong offset!");

}

