#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DebugMenu

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"
#include "OPP_structs.hpp"


namespace SDK::Params
{

// Function DebugMenu.DebugMenu_C.ExecuteUbergraph_DebugMenu
// 0x00F8 (0x00F8 - 0x0000)
struct DebugMenu_C_ExecuteUbergraph_DebugMenu final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_LoadClassAsset_Blocking_ReturnValue;      // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsUser_Widget;             // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_Create_ReturnValue;                       // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class URBMenuWidget*                          K2Node_DynamicCast_AsRB_Menu_Widget;               // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_ComponentBoundEvent_SelectedItem;           // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESelectInfo                                   K2Node_ComponentBoundEvent_SelectionType;          // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ARBPlayerState*                         CallFunc_GetLocalPlayerState_ReturnValue;          // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EActiveSkillType                              CallFunc_GetSelectedActiveSkill_ReturnValue;       // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5A[0x2];                                       // 0x005A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetSelectedIndex_ReturnValue;             // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ARBController*                          CallFunc_GetLocalPlayerController_ReturnValue;     // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EActiveSkillType                              CallFunc_Array_Get_Item;                           // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6A[0x6];                                       // 0x006A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftClassPtr<class UClass>                   K2Node_CustomEvent_MenuClass;                      // 0x0070(0x0028)(HasGetValueTypeHash)
	class UClass*                                 CallFunc_LoadClassAsset_Blocking_ReturnValue_1;    // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsUser_Widget_1;           // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess_1;                // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_Create_ReturnValue_1;                     // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CallFunc_LoadClassAsset_Blocking_ReturnValue_2;    // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class URBMenuWidget*                          K2Node_DynamicCast_AsRB_Menu_Widget_1;             // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C9[0x7];                                       // 0x00C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 K2Node_ClassDynamicCast_AsUser_Widget_2;           // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess_2;                // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_Create_ReturnValue_2;                     // 0x00E0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCustomizationMenu_C*                   K2Node_DynamicCast_AsCustomization_Menu;           // 0x00E8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(DebugMenu_C_ExecuteUbergraph_DebugMenu) == 0x000008, "Wrong alignment on DebugMenu_C_ExecuteUbergraph_DebugMenu");
static_assert(sizeof(DebugMenu_C_ExecuteUbergraph_DebugMenu) == 0x0000F8, "Wrong size on DebugMenu_C_ExecuteUbergraph_DebugMenu");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, EntryPoint) == 0x000000, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::EntryPoint' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, CallFunc_LoadClassAsset_Blocking_ReturnValue) == 0x000008, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::CallFunc_LoadClassAsset_Blocking_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, K2Node_ClassDynamicCast_AsUser_Widget) == 0x000010, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::K2Node_ClassDynamicCast_AsUser_Widget' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, K2Node_ClassDynamicCast_bSuccess) == 0x000018, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, CallFunc_Create_ReturnValue) == 0x000020, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, K2Node_DynamicCast_AsRB_Menu_Widget) == 0x000028, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::K2Node_DynamicCast_AsRB_Menu_Widget' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, K2Node_ComponentBoundEvent_SelectedItem) == 0x000038, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::K2Node_ComponentBoundEvent_SelectedItem' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, K2Node_ComponentBoundEvent_SelectionType) == 0x000048, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::K2Node_ComponentBoundEvent_SelectionType' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, CallFunc_GetLocalPlayerState_ReturnValue) == 0x000050, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::CallFunc_GetLocalPlayerState_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, CallFunc_IsValid_ReturnValue) == 0x000058, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, CallFunc_GetSelectedActiveSkill_ReturnValue) == 0x000059, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::CallFunc_GetSelectedActiveSkill_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, CallFunc_GetSelectedIndex_ReturnValue) == 0x00005C, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::CallFunc_GetSelectedIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, CallFunc_GetLocalPlayerController_ReturnValue) == 0x000060, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::CallFunc_GetLocalPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, CallFunc_Array_Get_Item) == 0x000068, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000069, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, K2Node_CustomEvent_MenuClass) == 0x000070, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::K2Node_CustomEvent_MenuClass' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, CallFunc_LoadClassAsset_Blocking_ReturnValue_1) == 0x000098, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::CallFunc_LoadClassAsset_Blocking_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, K2Node_ClassDynamicCast_AsUser_Widget_1) == 0x0000A0, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::K2Node_ClassDynamicCast_AsUser_Widget_1' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, K2Node_ClassDynamicCast_bSuccess_1) == 0x0000A8, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::K2Node_ClassDynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, CallFunc_Create_ReturnValue_1) == 0x0000B0, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, CallFunc_LoadClassAsset_Blocking_ReturnValue_2) == 0x0000B8, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::CallFunc_LoadClassAsset_Blocking_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, K2Node_DynamicCast_AsRB_Menu_Widget_1) == 0x0000C0, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::K2Node_DynamicCast_AsRB_Menu_Widget_1' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, K2Node_DynamicCast_bSuccess_1) == 0x0000C8, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, K2Node_ClassDynamicCast_AsUser_Widget_2) == 0x0000D0, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::K2Node_ClassDynamicCast_AsUser_Widget_2' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, K2Node_ClassDynamicCast_bSuccess_2) == 0x0000D8, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::K2Node_ClassDynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, CallFunc_Create_ReturnValue_2) == 0x0000E0, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::CallFunc_Create_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, K2Node_DynamicCast_AsCustomization_Menu) == 0x0000E8, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::K2Node_DynamicCast_AsCustomization_Menu' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_ExecuteUbergraph_DebugMenu, K2Node_DynamicCast_bSuccess_2) == 0x0000F0, "Member 'DebugMenu_C_ExecuteUbergraph_DebugMenu::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");

// Function DebugMenu.DebugMenu_C.LoadAndPushMenu
// 0x0028 (0x0028 - 0x0000)
struct DebugMenu_C_LoadAndPushMenu final
{
public:
	TSoftClassPtr<class UClass>                   MenuClass;                                         // 0x0000(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(DebugMenu_C_LoadAndPushMenu) == 0x000008, "Wrong alignment on DebugMenu_C_LoadAndPushMenu");
static_assert(sizeof(DebugMenu_C_LoadAndPushMenu) == 0x000028, "Wrong size on DebugMenu_C_LoadAndPushMenu");
static_assert(offsetof(DebugMenu_C_LoadAndPushMenu, MenuClass) == 0x000000, "Member 'DebugMenu_C_LoadAndPushMenu::MenuClass' has a wrong offset!");

// Function DebugMenu.DebugMenu_C.BndEvt__ActiveSkillsCombo_K2Node_ComponentBoundEvent_1_OnSelectionChangedEvent__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct DebugMenu_C_BndEvt__ActiveSkillsCombo_K2Node_ComponentBoundEvent_1_OnSelectionChangedEvent__DelegateSignature final
{
public:
	class FString                                 SelectedItem;                                      // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	ESelectInfo                                   SelectionType;                                     // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DebugMenu_C_BndEvt__ActiveSkillsCombo_K2Node_ComponentBoundEvent_1_OnSelectionChangedEvent__DelegateSignature) == 0x000008, "Wrong alignment on DebugMenu_C_BndEvt__ActiveSkillsCombo_K2Node_ComponentBoundEvent_1_OnSelectionChangedEvent__DelegateSignature");
static_assert(sizeof(DebugMenu_C_BndEvt__ActiveSkillsCombo_K2Node_ComponentBoundEvent_1_OnSelectionChangedEvent__DelegateSignature) == 0x000018, "Wrong size on DebugMenu_C_BndEvt__ActiveSkillsCombo_K2Node_ComponentBoundEvent_1_OnSelectionChangedEvent__DelegateSignature");
static_assert(offsetof(DebugMenu_C_BndEvt__ActiveSkillsCombo_K2Node_ComponentBoundEvent_1_OnSelectionChangedEvent__DelegateSignature, SelectedItem) == 0x000000, "Member 'DebugMenu_C_BndEvt__ActiveSkillsCombo_K2Node_ComponentBoundEvent_1_OnSelectionChangedEvent__DelegateSignature::SelectedItem' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_BndEvt__ActiveSkillsCombo_K2Node_ComponentBoundEvent_1_OnSelectionChangedEvent__DelegateSignature, SelectionType) == 0x000010, "Member 'DebugMenu_C_BndEvt__ActiveSkillsCombo_K2Node_ComponentBoundEvent_1_OnSelectionChangedEvent__DelegateSignature::SelectionType' has a wrong offset!");

// Function DebugMenu.DebugMenu_C.InitActiveSkillBox
// 0x0100 (0x0100 - 0x0000)
struct DebugMenu_C_InitActiveSkillBox final
{
public:
	EActiveSkillType                              CurrentSkill;                                      // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   SelectedSkill;                                     // 0x0008(0x0018)(Edit, BlueprintVisible)
	class UClass*                                 CurrentSkillClass;                                 // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_Conv_IntToByte_ReturnValue;               // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_GetValidValue_ReturnValue;                // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_Conv_IntToByte_ReturnValue_1;             // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x003A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_GetEnumeratorValueFromIndex_ReturnValue;  // 0x003B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_MakeLiteralInt_ReturnValue;               // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0058(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class ARBPlayerState*                         CallFunc_GetLocalPlayerState_ReturnValue;          // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EActiveSkillType                              CallFunc_GetSelectedActiveSkill_ReturnValue;       // 0x0071(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EActiveSkillType                              CallFunc_Array_Get_Item;                           // 0x0072(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_73[0x1];                                       // 0x0073(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x007A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7B[0x5];                                       // 0x007B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActiveSkillCommonParams               CallFunc_GetActiveSkillCommonParams_ReturnValue;   // 0x0080(0x0078)(ConstParm)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DebugMenu_C_InitActiveSkillBox) == 0x000008, "Wrong alignment on DebugMenu_C_InitActiveSkillBox");
static_assert(sizeof(DebugMenu_C_InitActiveSkillBox) == 0x000100, "Wrong size on DebugMenu_C_InitActiveSkillBox");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CurrentSkill) == 0x000000, "Member 'DebugMenu_C_InitActiveSkillBox::CurrentSkill' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, SelectedSkill) == 0x000008, "Member 'DebugMenu_C_InitActiveSkillBox::SelectedSkill' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CurrentSkillClass) == 0x000020, "Member 'DebugMenu_C_InitActiveSkillBox::CurrentSkillClass' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, Temp_int_Variable) == 0x000028, "Member 'DebugMenu_C_InitActiveSkillBox::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, Temp_int_Variable_1) == 0x00002C, "Member 'DebugMenu_C_InitActiveSkillBox::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_Conv_IntToByte_ReturnValue) == 0x000030, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_Conv_IntToByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_Add_IntInt_ReturnValue) == 0x000034, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_GetValidValue_ReturnValue) == 0x000038, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_GetValidValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_Conv_IntToByte_ReturnValue_1) == 0x000039, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_Conv_IntToByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x00003A, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_GetEnumeratorValueFromIndex_ReturnValue) == 0x00003B, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_GetEnumeratorValueFromIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_Conv_ByteToInt_ReturnValue) == 0x00003C, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, Temp_int_Loop_Counter_Variable) == 0x000040, "Member 'DebugMenu_C_InitActiveSkillBox::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_Add_IntInt_ReturnValue_1) == 0x000044, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, Temp_int_Array_Index_Variable) == 0x000048, "Member 'DebugMenu_C_InitActiveSkillBox::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_MakeLiteralInt_ReturnValue) == 0x00004C, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_MakeLiteralInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_Less_IntInt_ReturnValue) == 0x000050, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_Conv_TextToString_ReturnValue) == 0x000058, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_GetLocalPlayerState_ReturnValue) == 0x000068, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_GetLocalPlayerState_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_IsValid_ReturnValue) == 0x000070, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_GetSelectedActiveSkill_ReturnValue) == 0x000071, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_GetSelectedActiveSkill_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_Array_Get_Item) == 0x000072, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_Array_Length_ReturnValue) == 0x000074, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000078, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_Less_IntInt_ReturnValue_1) == 0x000079, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x00007A, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_GetActiveSkillCommonParams_ReturnValue) == 0x000080, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_GetActiveSkillCommonParams_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_InitActiveSkillBox, CallFunc_Array_Add_ReturnValue) == 0x0000F8, "Member 'DebugMenu_C_InitActiveSkillBox::CallFunc_Array_Add_ReturnValue' has a wrong offset!");

// Function DebugMenu.DebugMenu_C.CheckUseMinimalInventory
// 0x0001 (0x0001 - 0x0000)
struct DebugMenu_C_CheckUseMinimalInventory final
{
public:
	ECheckBoxState                                ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DebugMenu_C_CheckUseMinimalInventory) == 0x000001, "Wrong alignment on DebugMenu_C_CheckUseMinimalInventory");
static_assert(sizeof(DebugMenu_C_CheckUseMinimalInventory) == 0x000001, "Wrong size on DebugMenu_C_CheckUseMinimalInventory");
static_assert(offsetof(DebugMenu_C_CheckUseMinimalInventory, ReturnValue) == 0x000000, "Member 'DebugMenu_C_CheckUseMinimalInventory::ReturnValue' has a wrong offset!");

// Function DebugMenu.DebugMenu_C.GetLobbyVisibility
// 0x0018 (0x0018 - 0x0000)
struct DebugMenu_C_GetLobbyVisibility final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ARBLobbyPlayerController*               CallFunc_GetLocalLobbyPlayerController_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DebugMenu_C_GetLobbyVisibility) == 0x000008, "Wrong alignment on DebugMenu_C_GetLobbyVisibility");
static_assert(sizeof(DebugMenu_C_GetLobbyVisibility) == 0x000018, "Wrong size on DebugMenu_C_GetLobbyVisibility");
static_assert(offsetof(DebugMenu_C_GetLobbyVisibility, ReturnValue) == 0x000000, "Member 'DebugMenu_C_GetLobbyVisibility::ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_GetLobbyVisibility, Temp_bool_Variable) == 0x000001, "Member 'DebugMenu_C_GetLobbyVisibility::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_GetLobbyVisibility, Temp_byte_Variable) == 0x000002, "Member 'DebugMenu_C_GetLobbyVisibility::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_GetLobbyVisibility, Temp_byte_Variable_1) == 0x000003, "Member 'DebugMenu_C_GetLobbyVisibility::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_GetLobbyVisibility, CallFunc_GetLocalLobbyPlayerController_ReturnValue) == 0x000008, "Member 'DebugMenu_C_GetLobbyVisibility::CallFunc_GetLocalLobbyPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_GetLobbyVisibility, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'DebugMenu_C_GetLobbyVisibility::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_GetLobbyVisibility, K2Node_Select_Default) == 0x000011, "Member 'DebugMenu_C_GetLobbyVisibility::K2Node_Select_Default' has a wrong offset!");

// Function DebugMenu.DebugMenu_C.OnFocusReceived
// 0x01B8 (0x01B8 - 0x0000)
struct DebugMenu_C_OnFocusReceived final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FFocusEvent                            InFocusEvent;                                      // 0x0038(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FEventReply                            ReturnValue;                                       // 0x0040(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x00F8(0x00B8)()
	bool                                          CallFunc_BP_IsUsingGamepad_ReturnValue;            // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(DebugMenu_C_OnFocusReceived) == 0x000008, "Wrong alignment on DebugMenu_C_OnFocusReceived");
static_assert(sizeof(DebugMenu_C_OnFocusReceived) == 0x0001B8, "Wrong size on DebugMenu_C_OnFocusReceived");
static_assert(offsetof(DebugMenu_C_OnFocusReceived, MyGeometry) == 0x000000, "Member 'DebugMenu_C_OnFocusReceived::MyGeometry' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_OnFocusReceived, InFocusEvent) == 0x000038, "Member 'DebugMenu_C_OnFocusReceived::InFocusEvent' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_OnFocusReceived, ReturnValue) == 0x000040, "Member 'DebugMenu_C_OnFocusReceived::ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_OnFocusReceived, CallFunc_Handled_ReturnValue) == 0x0000F8, "Member 'DebugMenu_C_OnFocusReceived::CallFunc_Handled_ReturnValue' has a wrong offset!");
static_assert(offsetof(DebugMenu_C_OnFocusReceived, CallFunc_BP_IsUsingGamepad_ReturnValue) == 0x0001B0, "Member 'DebugMenu_C_OnFocusReceived::CallFunc_BP_IsUsingGamepad_ReturnValue' has a wrong offset!");

}

