#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Error_ConfirmCancelPopupWidget

#include "Basic.hpp"

#include "BaseConfirmCancelPopupWidget_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Error_ConfirmCancelPopupWidget.Error_ConfirmCancelPopupWidget_C
// 0x0000 (0x03F8 - 0x03F8)
class UError_ConfirmCancelPopupWidget_C : public UBaseConfirmCancelPopupWidget_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Error_ConfirmCancelPopupWidget_C">();
	}
	static class UError_ConfirmCancelPopupWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UError_ConfirmCancelPopupWidget_C>();
	}
};
static_assert(alignof(UError_ConfirmCancelPopupWidget_C) == 0x000008, "Wrong alignment on UError_ConfirmCancelPopupWidget_C");
static_assert(sizeof(UError_ConfirmCancelPopupWidget_C) == 0x0003F8, "Wrong size on UError_ConfirmCancelPopupWidget_C");

}

