#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FlipNumberCountDownMinus01_BP

#include "Basic.hpp"

#include "FlipNumberCountDownMinus01_BP_classes.hpp"
#include "FlipNumberCountDownMinus01_BP_parameters.hpp"


namespace SDK
{

// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.OnFlipNumber__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::OnFlipNumber__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "OnFlipNumber__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.OnFlipCompleted__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::OnFlipCompleted__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "OnFlipCompleted__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.ExecuteUbergraph_FlipNumberCountDown-01_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFlipNumberCountDownMinus01_BP_C::ExecuteUbergraph_FlipNumberCountDownMinus01_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "ExecuteUbergraph_FlipNumberCountDown-01_BP");

	Params::FlipNumberCountDownMinus01_BP_C_ExecuteUbergraph_FlipNumberCountDownMinus01_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.PlayFlipX2
// (BlueprintCallable, BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::PlayFlipX2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "PlayFlipX2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.playFlip
// (BlueprintCallable, BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::PlayFlip()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "playFlip");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.flipLoop
// (BlueprintCallable, BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::FlipLoop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "flipLoop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.xsetNumber
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Number                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFlipNumberCountDownMinus01_BP_C::XsetNumber(int32 Number)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "xsetNumber");

	Params::FlipNumberCountDownMinus01_BP_C_XsetNumber Parms{};

	Parms.Number = Number;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.resetAll
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Number                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFlipNumberCountDownMinus01_BP_C::ResetAll(int32 Number)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "resetAll");

	Params::FlipNumberCountDownMinus01_BP_C_ResetAll Parms{};

	Parms.Number = Number;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.Flip
// (BlueprintCallable, BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::Flip()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "Flip");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.Flip_Timeline__UpdateFunc
// (BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::Flip_Timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "Flip_Timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.Flip_Timeline__FinishedFunc
// (BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::Flip_Timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "Flip_Timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.FlipX2_timeline__UpdateFunc
// (BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::FlipX2_timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "FlipX2_timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.FlipX2_timeline__FinishedFunc
// (BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::FlipX2_timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "FlipX2_timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.FlipToInt
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Int                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ExtraLoops_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFlipNumberCountDownMinus01_BP_C::FlipToInt(int32 Int, int32 ExtraLoops_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "FlipToInt");

	Params::FlipNumberCountDownMinus01_BP_C_FlipToInt Parms{};

	Parms.Int = Int;
	Parms.ExtraLoops_0 = ExtraLoops_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.SetNewInt
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   NewDigit                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFlipNumberCountDownMinus01_BP_C::SetNewInt(int32 NewDigit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "SetNewInt");

	Params::FlipNumberCountDownMinus01_BP_C_SetNewInt Parms{};

	Parms.NewDigit = NewDigit;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.ResetFlapPositionAndMaterials
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::ResetFlapPositionAndMaterials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "ResetFlapPositionAndMaterials");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.SwapStaticmeshOrder
// (Public, BlueprintCallable, BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::SwapStaticmeshOrder()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "SwapStaticmeshOrder");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.Set Next Number on Mesh
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   CurrentNumber                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFlipNumberCountDownMinus01_BP_C::Set_Next_Number_on_Mesh(int32 CurrentNumber)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "Set Next Number on Mesh");

	Params::FlipNumberCountDownMinus01_BP_C_Set_Next_Number_on_Mesh Parms{};

	Parms.CurrentNumber = CurrentNumber;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.Next Number
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Int                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   IntOut                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFlipNumberCountDownMinus01_BP_C::Next_Number(int32 Int, int32* IntOut)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "Next Number");

	Params::FlipNumberCountDownMinus01_BP_C_Next_Number Parms{};

	Parms.Int = Int;

	UObject::ProcessEvent(Func, &Parms);

	if (IntOut != nullptr)
		*IntOut = Parms.IntOut;
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.findIntDistance
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Current_Int                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Target_Int                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Distance_0                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFlipNumberCountDownMinus01_BP_C::FindIntDistance(int32 Current_Int, int32 Target_Int, int32* Distance_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "findIntDistance");

	Params::FlipNumberCountDownMinus01_BP_C_FindIntDistance Parms{};

	Parms.Current_Int = Current_Int;
	Parms.Target_Int = Target_Int;

	UObject::ProcessEvent(Func, &Parms);

	if (Distance_0 != nullptr)
		*Distance_0 = Parms.Distance_0;
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.FlipIncrement
// (Public, BlueprintCallable, BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::FlipIncrement()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "FlipIncrement");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.FlipDecrement
// (Public, BlueprintCallable, BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::FlipDecrement()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "FlipDecrement");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.CheckValidity
// (Public, BlueprintCallable, BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::CheckValidity()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "CheckValidity");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.StartInfiniteFlip
// (Public, BlueprintCallable, BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::StartInfiniteFlip()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "StartInfiniteFlip");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.SetPlayRate
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   NewPlayRate                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFlipNumberCountDownMinus01_BP_C::SetPlayRate(float NewPlayRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "SetPlayRate");

	Params::FlipNumberCountDownMinus01_BP_C_SetPlayRate Parms{};

	Parms.NewPlayRate = NewPlayRate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.OnFlipTimelineFinished
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   CurrentInt_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFlipNumberCountDownMinus01_BP_C::OnFlipTimelineFinished(int32 CurrentInt_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "OnFlipTimelineFinished");

	Params::FlipNumberCountDownMinus01_BP_C_OnFlipTimelineFinished Parms{};

	Parms.CurrentInt_0 = CurrentInt_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.SetDitherFade
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFlipNumberCountDownMinus01_BP_C::SetDitherFade(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "SetDitherFade");

	Params::FlipNumberCountDownMinus01_BP_C_SetDitherFade Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FlipNumberCountDown-01_BP.FlipNumberCountDown-01_BP_C.DisableShadowAndReflexions
// (Public, BlueprintCallable, BlueprintEvent)

void AFlipNumberCountDownMinus01_BP_C::DisableShadowAndReflexions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FlipNumberCountDown-01_BP_C", "DisableShadowAndReflexions");

	UObject::ProcessEvent(Func, nullptr);
}

}

