#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GridElement

#include "Basic.hpp"


namespace SDK::Params
{

// Function GridElement.GridElement_C.IsElementEmpty
// 0x0001 (0x0001 - 0x0000)
struct GridElement_C_IsElementEmpty final
{
public:
	bool                                          bIsEmpty;                                          // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GridElement_C_IsElementEmpty) == 0x000001, "Wrong alignment on GridElement_C_IsElementEmpty");
static_assert(sizeof(GridElement_C_IsElementEmpty) == 0x000001, "Wrong size on GridElement_C_IsElementEmpty");
static_assert(offsetof(GridElement_C_IsElementEmpty, bIsEmpty) == 0x000000, "Member 'GridElement_C_IsElementEmpty::bIsEmpty' has a wrong offset!");

}

