#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Hidespot_DeskWoodMinus04_BP

#include "Basic.hpp"

#include "Hidespot_DeskWoodMinus04_BP_classes.hpp"
#include "Hidespot_DeskWoodMinus04_BP_parameters.hpp"


namespace SDK
{

// Function Hidespot_DeskWood-04_BP.Hidespot_DeskWood-04_BP_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AHidespot_DeskWoodMinus04_BP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Hidespot_DeskWood-04_BP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Hidespot_DeskWood-04_BP.Hidespot_DeskWood-04_BP_C.RandomizeDrawer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USceneComponent*                  Component                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Seed                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AHidespot_DeskWoodMinus04_BP_C::RandomizeDrawer(class USceneComponent* Component, int32 Seed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Hidespot_DeskWood-04_BP_C", "RandomizeDrawer");

	Params::Hidespot_DeskWoodMinus04_BP_C_RandomizeDrawer Parms{};

	Parms.Component = Component;
	Parms.Seed = Seed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Hidespot_DeskWood-04_BP.Hidespot_DeskWood-04_BP_C.FlipRelativeLocation
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USceneComponent*                  Component                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFlipX                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bFlixY                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bFlipZ                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AHidespot_DeskWoodMinus04_BP_C::FlipRelativeLocation(class USceneComponent* Component, bool bFlipX, bool bFlixY, bool bFlipZ)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Hidespot_DeskWood-04_BP_C", "FlipRelativeLocation");

	Params::Hidespot_DeskWoodMinus04_BP_C_FlipRelativeLocation Parms{};

	Parms.Component = Component;
	Parms.bFlipX = bFlipX;
	Parms.bFlixY = bFlixY;
	Parms.bFlipZ = bFlipZ;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Hidespot_DeskWood-04_BP.Hidespot_DeskWood-04_BP_C.FlipDesk
// (Public, BlueprintCallable, BlueprintEvent)

void AHidespot_DeskWoodMinus04_BP_C::FlipDesk()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Hidespot_DeskWood-04_BP_C", "FlipDesk");

	UObject::ProcessEvent(Func, nullptr);
}

}

