#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NarrativeScreenStandMinus01_BP

#include "Basic.hpp"

#include "NarrativeScreenBase_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NarrativeScreenStand-01_BP.NarrativeScreenStand-01_BP_C
// 0x0010 (0x03F0 - 0x03E0)
class ANarrativeScreenStandMinus01_BP_C final : public ANarrativeScreenBase_BP_C
{
public:
	class UStaticMeshComponent*                   StandSupportMinus01;                               // 0x03E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StandMinus01;                                      // 0x03E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NarrativeScreenStand-01_BP_C">();
	}
	static class ANarrativeScreenStandMinus01_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANarrativeScreenStandMinus01_BP_C>();
	}
};
static_assert(alignof(ANarrativeScreenStandMinus01_BP_C) == 0x000008, "Wrong alignment on ANarrativeScreenStandMinus01_BP_C");
static_assert(sizeof(ANarrativeScreenStandMinus01_BP_C) == 0x0003F0, "Wrong size on ANarrativeScreenStandMinus01_BP_C");
static_assert(offsetof(ANarrativeScreenStandMinus01_BP_C, StandSupportMinus01) == 0x0003E0, "Member 'ANarrativeScreenStandMinus01_BP_C::StandSupportMinus01' has a wrong offset!");
static_assert(offsetof(ANarrativeScreenStandMinus01_BP_C, StandMinus01) == 0x0003E8, "Member 'ANarrativeScreenStandMinus01_BP_C::StandMinus01' has a wrong offset!");

}

