#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SJ_ElectricSparkMinus01_BP

#include "Basic.hpp"

#include "SJ_ElectricSparkMinus01_BP_classes.hpp"
#include "SJ_ElectricSparkMinus01_BP_parameters.hpp"


namespace SDK
{

// Function SJ_ElectricSpark-01_BP.SJ_ElectricSpark-01_BP_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ASJ_ElectricSparkMinus01_BP_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SJ_ElectricSpark-01_BP_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SJ_ElectricSpark-01_BP.SJ_ElectricSpark-01_BP_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ASJ_ElectricSparkMinus01_BP_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SJ_ElectricSpark-01_BP_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SJ_ElectricSpark-01_BP.SJ_ElectricSpark-01_BP_C.Event_OnTriggered
// (Event, Public, BlueprintEvent)

void ASJ_ElectricSparkMinus01_BP_C::Event_OnTriggered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SJ_ElectricSpark-01_BP_C", "Event_OnTriggered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SJ_ElectricSpark-01_BP.SJ_ElectricSpark-01_BP_C.Event_OnUntriggered
// (Event, Public, BlueprintEvent)

void ASJ_ElectricSparkMinus01_BP_C::Event_OnUntriggered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SJ_ElectricSpark-01_BP_C", "Event_OnUntriggered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SJ_ElectricSpark-01_BP.SJ_ElectricSpark-01_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ASJ_ElectricSparkMinus01_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SJ_ElectricSpark-01_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SJ_ElectricSpark-01_BP.SJ_ElectricSpark-01_BP_C.ExecuteUbergraph_SJ_ElectricSpark-01_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASJ_ElectricSparkMinus01_BP_C::ExecuteUbergraph_SJ_ElectricSparkMinus01_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SJ_ElectricSpark-01_BP_C", "ExecuteUbergraph_SJ_ElectricSpark-01_BP");

	Params::SJ_ElectricSparkMinus01_BP_C_ExecuteUbergraph_SJ_ElectricSparkMinus01_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

