#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SJ_JukeBoxMinus01_BP

#include "Basic.hpp"

#include "SJ_JukeBoxMinus01_BP_classes.hpp"
#include "SJ_JukeBoxMinus01_BP_parameters.hpp"


namespace SDK
{

// Function SJ_JukeBox-01_BP.SJ_JukeBox-01_BP_C.SetPreviewAssetsVisibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Preview                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ASJ_JukeBoxMinus01_BP_C::SetPreviewAssetsVisibility(bool Preview)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SJ_JukeBox-01_BP_C", "SetPreviewAssetsVisibility");

	Params::SJ_JukeBoxMinus01_BP_C_SetPreviewAssetsVisibility Parms{};

	Parms.Preview = Preview;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SJ_JukeBox-01_BP.SJ_JukeBox-01_BP_C.JukeboxColors__FinishedFunc
// (BlueprintEvent)

void ASJ_JukeBoxMinus01_BP_C::JukeboxColors__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SJ_JukeBox-01_BP_C", "JukeboxColors__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SJ_JukeBox-01_BP.SJ_JukeBox-01_BP_C.JukeboxColors__UpdateFunc
// (BlueprintEvent)

void ASJ_JukeBoxMinus01_BP_C::JukeboxColors__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SJ_JukeBox-01_BP_C", "JukeboxColors__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SJ_JukeBox-01_BP.SJ_JukeBox-01_BP_C.Event_OnTriggered
// (Event, Public, BlueprintEvent)

void ASJ_JukeBoxMinus01_BP_C::Event_OnTriggered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SJ_JukeBox-01_BP_C", "Event_OnTriggered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SJ_JukeBox-01_BP.SJ_JukeBox-01_BP_C.Event_OnUntriggered
// (Event, Public, BlueprintEvent)

void ASJ_JukeBoxMinus01_BP_C::Event_OnUntriggered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SJ_JukeBox-01_BP_C", "Event_OnUntriggered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SJ_JukeBox-01_BP.SJ_JukeBox-01_BP_C.Event_OnResetStage
// (Event, Public, BlueprintEvent)

void ASJ_JukeBoxMinus01_BP_C::Event_OnResetStage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SJ_JukeBox-01_BP_C", "Event_OnResetStage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SJ_JukeBox-01_BP.SJ_JukeBox-01_BP_C.ExecuteUbergraph_SJ_JukeBox-01_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASJ_JukeBoxMinus01_BP_C::ExecuteUbergraph_SJ_JukeBoxMinus01_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SJ_JukeBox-01_BP_C", "ExecuteUbergraph_SJ_JukeBox-01_BP");

	Params::SJ_JukeBoxMinus01_BP_C_ExecuteUbergraph_SJ_JukeBoxMinus01_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

