#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Spectra_ActiveSkill_BP

#include "Basic.hpp"

#include "Spectra_ActiveSkill_BP_classes.hpp"
#include "Spectra_ActiveSkill_BP_parameters.hpp"


namespace SDK
{

// Function Spectra_ActiveSkill_BP.Spectra_ActiveSkill_BP_C.ExecuteUbergraph_Spectra_ActiveSkill_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASpectra_ActiveSkill_BP_C::ExecuteUbergraph_Spectra_ActiveSkill_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Spectra_ActiveSkill_BP_C", "ExecuteUbergraph_Spectra_ActiveSkill_BP");

	Params::Spectra_ActiveSkill_BP_C_ExecuteUbergraph_Spectra_ActiveSkill_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Spectra_ActiveSkill_BP.Spectra_ActiveSkill_BP_C.Event_OnForceDeactivatedEffectTriggered
// (Event, Public, BlueprintEvent)

void ASpectra_ActiveSkill_BP_C::Event_OnForceDeactivatedEffectTriggered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Spectra_ActiveSkill_BP_C", "Event_OnForceDeactivatedEffectTriggered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Spectra_ActiveSkill_BP.Spectra_ActiveSkill_BP_C.Event_OnVisionActiveChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsActive                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bFullEffect                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ASpectra_ActiveSkill_BP_C::Event_OnVisionActiveChanged(bool IsActive, bool bFullEffect)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Spectra_ActiveSkill_BP_C", "Event_OnVisionActiveChanged");

	Params::Spectra_ActiveSkill_BP_C_Event_OnVisionActiveChanged Parms{};

	Parms.IsActive = IsActive;
	Parms.bFullEffect = bFullEffect;

	UObject::ProcessEvent(Func, &Parms);
}

}

