#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Stairs2_BP

#include "Basic.hpp"

#include "Stairs_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Stairs2_BP.Stairs2_BP_C
// 0x0000 (0x0478 - 0x0478)
class AStairs2_BP_C final : public AStairs_BP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Stairs2_BP_C">();
	}
	static class AStairs2_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AStairs2_BP_C>();
	}
};
static_assert(alignof(AStairs2_BP_C) == 0x000008, "Wrong alignment on AStairs2_BP_C");
static_assert(sizeof(AStairs2_BP_C) == 0x000478, "Wrong size on AStairs2_BP_C");

}

