#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StaticmeshArray_Stuc

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct StaticmeshArray_Stuc.StaticmeshArray_Stuc
// 0x0010 (0x0010 - 0x0000)
struct FStaticmeshArray_Stuc final
{
public:
	TArray<class UStaticMeshComponent*>           StaticMeshComponentArray_6_9C8495664E7C1BA1C74A1793046FA186; // 0x0000(0x0010)(Edit, BlueprintVisible, ContainsInstancedReference)
};
static_assert(alignof(FStaticmeshArray_Stuc) == 0x000008, "Wrong alignment on FStaticmeshArray_Stuc");
static_assert(sizeof(FStaticmeshArray_Stuc) == 0x000010, "Wrong size on FStaticmeshArray_Stuc");
static_assert(offsetof(FStaticmeshArray_Stuc, StaticMeshComponentArray_6_9C8495664E7C1BA1C74A1793046FA186) == 0x000000, "Member 'FStaticmeshArray_Stuc::StaticMeshComponentArray_6_9C8495664E7C1BA1C74A1793046FA186' has a wrong offset!");

}

