#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TrialChainingRecapEntry

#include "Basic.hpp"

#include "TrialChainingRecapEntry_classes.hpp"
#include "TrialChainingRecapEntry_parameters.hpp"


namespace SDK
{

// Function TrialChainingRecapEntry.TrialChainingRecapEntry_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UTrialChainingRecapEntry_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrialChainingRecapEntry_C", "OnFocusReceived");

	Params::TrialChainingRecapEntry_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function TrialChainingRecapEntry.TrialChainingRecapEntry_C.Setup
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       TrialPicture_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TrialIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             TrialName_0                                            (BlueprintVisible, BlueprintReadOnly, Parm)
// TArray<class URBVariatorInfo*>          VariatorsInfos                                         (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// float                                   GroupScore                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   PlayerScore_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTrialChainingRecapEntry_C::Setup(class UTexture2D* TrialPicture_0, int32 TrialIndex, const class FText& TrialName_0, TArray<class URBVariatorInfo*>& VariatorsInfos, float GroupScore, float PlayerScore_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrialChainingRecapEntry_C", "Setup");

	Params::TrialChainingRecapEntry_C_Setup Parms{};

	Parms.TrialPicture_0 = TrialPicture_0;
	Parms.TrialIndex = TrialIndex;
	Parms.TrialName_0 = std::move(TrialName_0);
	Parms.VariatorsInfos = std::move(VariatorsInfos);
	Parms.GroupScore = GroupScore;
	Parms.PlayerScore_0 = PlayerScore_0;

	UObject::ProcessEvent(Func, &Parms);

	VariatorsInfos = std::move(Parms.VariatorsInfos);
}

}

